image: registry.cn-shanghai.aliyuncs.com/choerodon-tools/cibase:0.9.1

stages:
  - build
  - release

maven-build:
  stage: build
  script:
    - update_pom_version
    - mvn package -U -DskipTests=true
    - cp target/app-tests.jar ./app-tests.jar
    - docker_build

release:
  stage: release
  script:
    - chart_build

.auto_devops: &auto_devops |
    http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
    if [ "$http_status_code" != "200" ]; then
      cat .auto_devops.sh
      exit 1
    fi
    source .auto_devops.sh
    function docker_build(){
        chmod +x ${1:-"."}/run.sh
        docker login -u ${DOCKER_USER} -p ${DOCKER_PWD} ${DOCKER_REGISTRY}
        docker build -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"."}
        docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    }

before_script:
  - *auto_devops